data:
#    name: 'synthetic_shapes'
    dataset: 'CubemapDataset'
    primitives: 'all'
    not_warped_images: False   ## True if for generating DB or inference
    preprocessing: 
        resize: [1024, 1024]

front_end_model: 'Train_model_frontend_cubemap'  # 'Train_model_frontend'

model:
    train_only_descriptor: True  #########
    name: 'SuperPointNet_cubemap'
    params: {
    }
    detector_loss:
        loss_type: 'softmax'

    batch_size:  1 # 64
    eval_batch_size: 1
    learning_rate: 0.001

    kernel_reg: 0.
    detection_threshold: 0.001 # 1/65
    nms: 4
    # lambda_loss: 0 # disable descriptor loss
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4 # 4, 7.5
            lambda_d: 800 # 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 1000
            num_masked_non_matches_per_match: 100
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.5'

retrain: False # set true for new model
reset_iter: True

train_iter: 2000 # 200000
tensorboard_interval: 1000 # 200
print_interval: 10
save_interval: 20 # 2000
validation_interval: 10 # one validation of entire val set every N training steps
validation_size: 1
train_show_interval: 10 # one show of the current training from to Tensorboard every N training steps
seed: 0

# pretrained: 'logs/magicpoint_synth_t2/checkpoints/3channel.pth.tar'
pretrained: 'logs/iter333_ce/checkpoints/RD_230504_091857_iter334_checkpoint.pth.tar'
